name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.2

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Gradle Wrapper
      run: |
        # Generate gradle wrapper
        gradle wrapper --gradle-version 7.6.1

    - name: Build SSDMobilenet APK
      run: ./gradlew assembleSSDMobilenetRelease --stacktrace

    - name: Build CaffeSSD APK
      run: ./gradlew assembleCaffeSSDRelease --stacktrace

    - name: Get version name
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "version=dev-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release and Upload APKs
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        files: |
          app/build/outputs/apk/SSDMobilenet/release/app-SSDMobilenet-release-unsigned.apk
          app/build/outputs/apk/CaffeSSD/release/app-CaffeSSD-release-unsigned.apk